[package]
name = "rust-alignment-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-primes = "0.3.0"
num-bigint = "0.4"
num-traits = "0.2.19"
num = "0.4.3"
rand = "0.8.5"
